# This file was generated by GoReleaser. DO NOT EDIT.
cask "depviz" do
  name "depviz"
  desc "Visualise Go and JS/TS project dependencies as an interactive HTML map"
  homepage "https://github.com/jtoloui/depviz"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depviz"

  on_macos do
    on_intel do
      url "https://github.com/jtoloui/depviz/releases/download/v#{version}/depviz_Darwin_x86_64.tar.gz"
      sha256 "e35c0986e80562504b1fabc145a52acf906320961b5c6dc0a8f9f35ceaeecbb6"
    end
    on_arm do
      url "https://github.com/jtoloui/depviz/releases/download/v#{version}/depviz_Darwin_arm64.tar.gz"
      sha256 "4402dfd322c3201bfb081f97c55d9405d77572c8c826ef35230309503e4e4584"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depviz"]
    end
  end

  # No zap stanza required
end
