# This file was generated by GoReleaser. DO NOT EDIT.
cask "depviz" do
  name "depviz"
  desc "Visualise Go and JS/TS project dependencies as an interactive HTML map"
  homepage "https://github.com/jtoloui/depviz"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depviz"

  on_macos do
    on_intel do
      url "https://github.com/jtoloui/depviz/releases/download/v#{version}/depviz_Darwin_x86_64.tar.gz"
      sha256 "e5daad09a13f3ce74a08d66f13148ff14528d16de2b8bb8a58465c39a61a3bc8"
    end
    on_arm do
      url "https://github.com/jtoloui/depviz/releases/download/v#{version}/depviz_Darwin_arm64.tar.gz"
      sha256 "7483df0f81a7d5920dde71c850aa99336ba00fcb26441db7c76df27b8901c97c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depviz"]
    end
  end

  # No zap stanza required
end
