# This file was generated by GoReleaser. DO NOT EDIT.
cask "depviz" do
  name "depviz"
  desc "Visualise Go and JS/TS project dependencies as an interactive HTML map"
  homepage "https://github.com/jtoloui/depviz"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depviz"

  on_macos do
    on_intel do
      url "https://github.com/jtoloui/depviz/releases/download/v#{version}/depviz_Darwin_x86_64.tar.gz"
      sha256 "151f4d2d759de2930f31912ed2410b910cb41be6c8347127b46f500cb8b817cf"
    end
    on_arm do
      url "https://github.com/jtoloui/depviz/releases/download/v#{version}/depviz_Darwin_arm64.tar.gz"
      sha256 "784e5852b2b2521b45c616b9523ed502356ec86750f178c50530567ebe8bdb50"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depviz"]
    end
  end

  # No zap stanza required
end
